# Collecting Anime Data

## Introduction

The main goal of this project is to build a web app of **Top 10 Animes Across Years & Recommendations**. This app can guide and help people who are interested in japanese animations and are trying to start watching.

In order to build the app, animes data are needed. In this part, the data collecting from API will be handled.


*Note: During throughout the project, Anime means Japanese Animation Cartoon.*

# Imports

### Import necessary libraries and packages

To start collect the data, first, relevant Python libraries and modules are imported.

In order to get anime movies, `jikanpy` modules, which handles API requests for getting the necessary data, will be used.

For constructing the data frame and exporting it as the CSV file, `pandas` library will be used.

In [ ]:
# Importing libraries and packages

import time
import pandas as pd
import numpy as np
from jikanpy import Jikan

# Data Collection

### Constructing Jikan Class Instance

After importing the necessary packages and modules, start creating a Jikan class instance from the jikanpy library. The methods of the created class instance will handle API requests.

In [2]:
# Creating Jikan class instance

jikan = Jikan()

### Building Functions

First function: `get_seasonal_animes(year, season)`
- The function requires two parameters: `year` and `season`.
    - `year` parameter takes which year of the data to be searched.
    - `season` parameter takes which season of the data to be searched.
- The function collects all animes data according to its parameters through different pages.
- The function returns all animes based on the input parameters.

In [3]:
def get_seasonal_animes(year, 
                        season):
    '''
    This function will return the seasonal animes list according to its year and season parameter input.
    '''
    
    seasonal_animes = []
    n = 0
    has_next_page = True

    # add to the seasonal_animes list until there is a next page in the pagination
    while has_next_page:
        n += 1
        animes_in_current_page = jikan.seasons(year=year, season=season, page=n)
        seasonal_animes.extend(animes_in_current_page['data'])
        has_next_page = True if animes_in_current_page['pagination']['has_next_page'] else False

        # the function needs to wait about 2 seconds in order not to pass API request limit per second.
        time.sleep(2)

    return seasonal_animes

Second function: `get_animes_range_of_years(start_year, end_year = None):`
- The function requires two parameters: `start_year` and `end_year`.
    - `start` parameter takes which lower limit of the year of the data to be searched.
    - `end_year` parameter takes which upper limit of the year of the data to be searched. If it is not provided, make it `None` as default.
- The function collects all animes data in the range of years according to its parameters.
- The function returns all animes based on the input parameters.

In [4]:
def get_animes_range_of_years(start_year, 
                              end_year = None):
    '''
    This function will return all animes list according to its range of years from the parameter input.
    '''

    # checking the end_year parameter is provided or not.
    # If it is not provided, the function assumes the user want to get the data from only one year, so makes start year and end year equal.
    # It it is provided, noting needs to be done and keep the end_year as it is from the input.
    end_year = start_year if not end_year else end_year
    all_animes = []

    # getting data from each year in the input ranges of years
    for year in range(start_year, end_year + 1):
        # In a whole year, there are four season. Therefore, get_seasonal_animes function will help to get data from each season.
        whole_year_animes = get_seasonal_animes(year, 'spring') + \
                            get_seasonal_animes(year, 'summer') + \
                            get_seasonal_animes(year, 'fall') + \
                            get_seasonal_animes(year, 'winter')
        
        all_animes.extend(whole_year_animes)
        print(f'## Collecting {year} data finished!')

    return all_animes

### Calling functions

For this project, all animes data in from `2006` to `2022` are needed. 

Therefore, `2006` is set as `start_year` argument and `2022` as `end_year` argument and call the function `get_animes_range_of_years`.

It takes a while to get all necessary data as the required data size is large.


### Building DataFrame

After collecting the data from the API has finished, the data is made as DataFrame with the help of `pandas` library.

In [5]:
anime_data_2006_2022 = get_animes_range_of_years(2006, 2022)
df = pd.json_normalize(anime_data_2006_2022)

## Collecting 2006 data finished!
## Collecting 2007 data finished!
## Collecting 2008 data finished!
## Collecting 2009 data finished!
## Collecting 2010 data finished!
## Collecting 2011 data finished!
## Collecting 2012 data finished!
## Collecting 2013 data finished!
## Collecting 2014 data finished!
## Collecting 2015 data finished!
## Collecting 2016 data finished!
## Collecting 2017 data finished!
## Collecting 2018 data finished!
## Collecting 2019 data finished!
## Collecting 2020 data finished!
## Collecting 2021 data finished!
## Collecting 2022 data finished!

# Data Exploration

### Display the first 5 rows of the data

Next, we will explore the dataset. To begin, display the first 5 rows of the data to get an understanding of how the dataset is structured.

In [6]:
df.head()

,mal_id,url,approved,titles,title,title_english,title_japanese,title_synonyms,type,source,...,aired.prop.from.month,aired.prop.from.year,aired.prop.to.day,aired.prop.to.month,aired.prop.to.year,aired.string,broadcast.day,broadcast.time,broadcast.timezone,broadcast.string
0,853,https://myanimelist.net/anime/853/Ouran_Koukou...,True,"[{'type': 'Default', 'title': 'Ouran Koukou Ho...",Ouran Koukou Host Club,Ouran High School Host Club,桜蘭高校ホスト部,"[Ohran Koko Host Club, Ouran Koukou Hosutobu, ...",TV,Manga,...,4,2006,27.0,9.0,2006.0,"Apr 5, 2006 to Sep 27, 2006",Wednesdays,00:50,Asia/Tokyo,Wednesdays at 00:50 (JST)
1,918,https://myanimelist.net/anime/918/Gintama,True,"[{'type': 'Default', 'title': 'Gintama'}, {'ty...",Gintama,Gintama,銀魂,"[Gin Tama, Silver Soul, Yorinuki Gintama-san]",TV,Manga,...,4,2006,25.0,3.0,2010.0,"Apr 4, 2006 to Mar 25, 2010",Thursdays,18:00,Asia/Tokyo,Thursdays at 18:00 (JST)
2,889,https://myanimelist.net/anime/889/Black_Lagoon,True,"[{'type': 'Default', 'title': 'Black Lagoon'},...",Black Lagoon,Black Lagoon,BLACK LAGOON,[],TV,Manga,...,4,2006,25.0,6.0,2006.0,"Apr 9, 2006 to Jun 25, 2006",Sundays,02:35,Asia/Tokyo,Sundays at 02:35 (JST)
3,849,https://myanimelist.net/anime/849/Suzumiya_Har...,True,"[{'type': 'Default', 'title': 'Suzumiya Haruhi...",Suzumiya Haruhi no Yuuutsu,The Melancholy of Haruhi Suzumiya,涼宮ハルヒの憂鬱,[Suzumiya Haruhi no Yuuutsu],TV,Light novel,...,4,2006,3.0,7.0,2006.0,"Apr 3, 2006 to Jul 3, 2006",Mondays,00:00,Asia/Tokyo,Mondays at 00:00 (JST)
4,934,https://myanimelist.net/anime/934/Higurashi_no...,True,"[{'type': 'Default', 'title': 'Higurashi no Na...",Higurashi no Naku Koro ni,Higurashi: When They Cry,ひぐらしのなく頃に,"[When the Cicadas Cry, The Moment the Cicadas ...",TV,Visual novel,...,4,2006,27.0,9.0,2006.0,"Apr 5, 2006 to Sep 27, 2006",Wednesdays,01:30,Asia/Tokyo,Wednesdays at 01:30 (JST)

### Check the shape of the data

In order to know how large the dataset is, `shape` property can help us.

In [7]:
df.shape

(16337, 59)

### List the columns

The `columns` property can let us know what columns there are in the dataframe.

In [8]:
df.columns

Index(['mal_id', 'url', 'approved', 'titles', 'title', 'title_english',
       'title_japanese', 'title_synonyms', 'type', 'source', 'episodes',
       'status', 'airing', 'duration', 'rating', 'score', 'scored_by', 'rank',
       'popularity', 'members', 'favorites', 'synopsis', 'background',
       'season', 'year', 'producers', 'licensors', 'studios', 'genres',
       'explicit_genres', 'themes', 'demographics', 'images.jpg.image_url',
       'images.jpg.small_image_url', 'images.jpg.large_image_url',
       'images.webp.image_url', 'images.webp.small_image_url',
       'images.webp.large_image_url', 'trailer.youtube_id', 'trailer.url',
       'trailer.embed_url', 'trailer.images.image_url',
       'trailer.images.small_image_url', 'trailer.images.medium_image_url',
       'trailer.images.large_image_url', 'trailer.images.maximum_image_url',
       'aired.from', 'aired.to', 'aired.prop.from.day',
       'aired.prop.from.month', 'aired.prop.from.year', 'aired.prop.to.day',
       'aired.prop.to.month', 'aired.prop.to.year', 'aired.string',
       'broadcast.day', 'broadcast.time', 'broadcast.timezone',
       'broadcast.string'],
      dtype='object')

### Get basic information about the dataset

To understand more about what the dataset involves, get basic information about the dataset, including the data type of values in each column,
the `info()` function from `pandas` can provide.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16337 entries, 0 to 16336
Data columns (total 59 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   mal_id                            16337 non-null  int64
 1   url                               16337 non-null  object
 2   approved                          16337 non-null  bool
 3   titles                            16337 non-null  object
 4   title                             16337 non-null  object
 5   title_english                     7135 non-null   object
 6   title_japanese                    16279 non-null  object
 7   title_synonyms                    16337 non-null  object
 8   type                              16337 non-null  object
 9   source                            16337 non-null  object
 10  episodes                          16191 non-null  float64
 11  status                            16337 non-null  object
 12  airing                            16337 non-null  bool
 13  duration                          16337 non-null  object
 14  rating                            16190 non-null  object
 15  score                             10787 non-null  float64
 16  scored_by                         10787 non-null  float64
 17  rank                              12730 non-null  float64
 18  popularity                        16337 non-null  int64
 19  members                           16337 non-null  int64
 20  favorites                         16337 non-null  int64
 21  synopsis                          13253 non-null  object
 22  background                        1850 non-null   object
 23  season                            3661 non-null   object
 24  year                              3661 non-null   float64
 25  producers                         16337 non-null  object
 26  licensors                         16337 non-null  object
 27  studios                           16337 non-null  object
 28  genres                            16337 non-null  object
 29  explicit_genres                   16337 non-null  object
 30  themes                            16337 non-null  object
 31  demographics                      16337 non-null  object
 32  images.jpg.image_url              16337 non-null  object
 33  images.jpg.small_image_url        16337 non-null  object
 34  images.jpg.large_image_url        16337 non-null  object
 35  images.webp.image_url             16337 non-null  object
 36  images.webp.small_image_url       16337 non-null  object
 37  images.webp.large_image_url       16337 non-null  object
 38  trailer.youtube_id                3740 non-null   object
 39  trailer.url                       3740 non-null   object
 40  trailer.embed_url                 3741 non-null   object
 41  trailer.images.image_url          3740 non-null   object
 42  trailer.images.small_image_url    3740 non-null   object
 43  trailer.images.medium_image_url   3740 non-null   object
 44  trailer.images.large_image_url    3740 non-null   object
 45  trailer.images.maximum_image_url  3740 non-null   object
 46  aired.from                        16337 non-null  object
 47  aired.to                          6858 non-null   object
 48  aired.prop.from.day               16337 non-null  int64
 49  aired.prop.from.month             16337 non-null  int64
 50  aired.prop.from.year              16337 non-null  int64
 51  aired.prop.to.day                 6858 non-null   float64
 52  aired.prop.to.month               6858 non-null   float64
 53  aired.prop.to.year                6858 non-null   float64
 54  aired.string                      16337 non-null  object
 55  broadcast.day                     2427 non-null   object
 56  broadcast.time                    2427 non-null   object
 57  broadcast.timezone                2427 non-null   object
 58  broadcast.string                  5033 non-null   object
dtypes: bool(2), float64(8), int64(7), object(42)
memory usage: 7.1+ MB

### Finding the descriptive statistics

The `describe()` function can help us to find the descriptive statistics and structure of the numeric columns in the dataset.

In [12]:
df.describe().T # T means transposing rows into columns and vice versa.

,count,mean,std,min,25%,50%,75%,max
mal_id,16337.0,34679.776030,15519.817037,356.00,24973.00,37921.00,46916.00,57879.00
episodes,16191.0,13.648323,33.821659,1.00,1.00,2.00,13.00,1664.00
score,10787.0,6.477158,0.894568,2.33,5.84,6.47,7.14,9.09
scored_by,10787.0,39631.189858,138933.921183,101.00,410.50,2471.00,17379.00,2754086.00
rank,12730.0,10020.123095,6062.839913,2.00,4639.25,9967.50,15387.25,20440.00
popularity,16337.0,12638.793842,7919.280985,1.00,5363.00,12626.00,19747.00,26089.00
members,16337.0,50339.307890,190065.515139,17.00,207.00,1169.00,14788.00,3880951.00
favorites,16337.0,563.967436,5013.564300,0.00,0.00,1.00,29.00,223131.00
year,3661.0,2014.680142,4.722127,2006.00,2011.00,2015.00,2018.00,2022.00
aired.prop.from.day,16337.0,12.831548,9.843854,1.00,4.00,11.00,22.00,31.00
aired.prop.from.month,16337.0,5.877701,3.658152,1.00,3.00,6.00,9.00,12.00
aired.prop.from.year,16337.0,2015.086858,4.587714,2005.00,2012.00,2016.00,2019.00,2022.00
aired.prop.to.day,6858.0,19.042578,9.278882,1.00,12.00,22.00,26.00,31.00
aired.prop.to.month,6858.0,6.752406,3.580316,1.00,3.00,7.00,10.00,12.00
aired.prop.to.year,6858.0,2015.419510,4.636944,2006.00,2012.00,2016.00,2019.00,2024.00

# Exporting the DataFrame

### Output the dataset into the CSV file

In order to export the dataset to use, `to_csv()` function from `pandas` can make the process easy.

In [11]:
df.to_csv('anime_data_2006_2022.csv', index=False)

# Summary

In this notebook, we made the data collection process with step by step: determining what libraries and packages to use, importing them, making class instance to handle API requests, constructing the helper functions, collecting the data with the help of the functions, building dataframe with pandas, initial exploration and exporting the dataframe as CSV file.

In the next part, we will approach the data with **Exploratory Data Analysis (EDA)** process.